### ISSUE TITLE
This is full device tree?

### ISSUE THREAD

**Issue by skinzor** [aapav01/android_device_samsung_j5nlte#1]
Hello. Im new to github and building roms. Im sorry if im asking in wrong place. Can you tell me if this is the full device tree for j5nlte? Im waiting for an reply. Thank you!

Have a nice day!

Robert.

**Comment by aapav01** [comment]
sorry..

just revert

https://github.com/aapav01/android_device_samsung_j5nlte/commit/197cdb64e4096d40bb414024ad3e6390a80da6c8

and change this
https://github.com/aapav01/android_device_samsung_j5nlte/blob/cm-12.1/BoardConfig.mk#L19

line ms01lte to j5nlte

.... this will help u :)

Aapav

**Comment by skinzor** [comment]
Hello. After i do that change, the device tree is full? i mean, nothing is missing? Im asking because i saw on github at other phoens that device tree has some folders too.

I have downloaded the kernel source from samsung site and now i see that i need the vendor tree, but i have no idea how to get it :D 

Thank you!


Robert.

**Comment by aapav01** [comment]
https://github.com/aapav01/android_device_samsung_j5nlte/commit/7b9b6a6ab2f543963e0ca62bfda084dd6bf1894f

**Comment by aapav01** [comment]
done

**Comment by skinzor** [comment]
Thank you! Im sorry if im annoying you, but im an newbie :D 

Any idea how to get the vendor tree?

**Comment by aapav01** [comment]
it a recovery only.. 

for cm-12.1 bring up

come on gtalk (aapav01@gmail.com) will talk there for the bring up

**Comment by skinzor** [comment]
okay, 1 minute please

**Comment by ganeshi4u** [comment]
Hey hy..am also trying to build rom for this device...im also searching for vendor tree...i hav no idea where to get it from...plz smeone hlp me...
Am a newbie 😃

**Comment by skinzor** [comment]
@aapav01 i have sent you an request on google talk.

**Comment by aapav01** [comment]
no request yet !!

which device u have

galaxy J5 MOdel no. ??

**Comment by skinzor** [comment]
i have J500FN

**Comment by skinzor** [comment]
Try you to contact me: robertica95@gmail.com

**Comment by microtik88** [comment]
No one can buil rr cm12 for samsung j5. thank you

https://github.com/ResurrectionRemix/platform_manifest/blob/lollipop/README.mkdn
